/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as RobotsDottxtRouteImport } from './app/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './app/sitemap[.]xml'
import { Route as LlmsIndexRouteImport } from './app/llms/index'
import { Route as LlmsJsonRouteImport } from './app/llms/json'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsIndexRoute = LlmsIndexRouteImport.update({
  id: '/llms/',
  path: '/llms/',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsJsonRoute = LlmsJsonRouteImport.update({
  id: '/llms/json',
  path: '/llms/json',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/llms/json': typeof LlmsJsonRoute
  '/llms/': typeof LlmsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/llms/json': typeof LlmsJsonRoute
  '/llms': typeof LlmsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/llms/json': typeof LlmsJsonRoute
  '/llms/': typeof LlmsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/robots.txt' | '/sitemap.xml' | '/llms/json' | '/llms/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/robots.txt' | '/sitemap.xml' | '/llms/json' | '/llms'
  id:
    '__root__' | '/' | '/robots.txt' | '/sitemap.xml' | '/llms/json' | '/llms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LlmsJsonRoute: typeof LlmsJsonRoute
  LlmsIndexRoute: typeof LlmsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms/': {
      id: '/llms/'
      path: '/llms'
      fullPath: '/llms/'
      preLoaderRoute: typeof LlmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms/json': {
      id: '/llms/json'
      path: '/llms/json'
      fullPath: '/llms/json'
      preLoaderRoute: typeof LlmsJsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LlmsJsonRoute: LlmsJsonRoute,
  LlmsIndexRoute: LlmsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
