/** Prompt blocks for PR description generation (Mermaid + file walkthrough). */

export const descriptionMermaidGuidance = [
  "## Changes diagram (changesDiagram)",
  "",
  "Optional fenced ```mermaid flowchart LR``` showing one connected story across the main change.",
  "Omit changesDiagram when a diagram would not help reviewers.",
  "",
  "### Syntax rules (GitHub must render it)",
  "- First line inside the fence: `flowchart LR` (preferred) or `flowchart TB`.",
  '- Use simple node ids (A, B, C…). Put human text in **quoted** labels: `A["Load course"]`.',
  "- Do **not** use `/subroutine/` node shapes — slashes in labels break GitHub's parser.",
  "- Do **not** put `/`, backticks, or unescaped `()` inside unquoted `[labels]`.",
  "- One connected graph only (every node reachable); for large PRs use ≤8 nodes and group steps.",
  "- Edges: `A --> B` only (no exotic arrow types).",
  "",
  "### Large PR tips",
  '- Summarize areas (e.g. "Admin API", "Course builder") instead of listing every file.',
  "- Prefer one trunk flow with short labels over multiple disconnected mini-flows.",
  "",
  "### Good example",
  "```mermaid",
  "flowchart LR",
  '  A["Admin form save"] --> B["Render-safe redirect"]',
  '  B --> C["Next navigation"]',
  '  D["Course builder"] --> E["Paginated sections"]',
  '  E --> F["Lesson + subsection data"]',
  "```",
  "",
  "### Bad (will fail on GitHub)",
  "- `K[/api/admin-users/list proxy]` — slashes inside brackets.",
  "- Mixing four unrelated flows with no edges between them.",
  "- Labels with backticks or nested quotes.",
].join("\n");

export const descriptionFileWalkthroughGuidance = [
  "## File walkthrough (prFiles)",
  "",
  "Optional up to 20 entries. Each entry becomes a **collapsed** accordion in the PR body:",
  "- `changesTitle` (5–10 words) is the visible summary line.",
  "- `filename` and `changesSummary` bullets appear only when the reader expands that entry.",
  "- Use `label` to group entries (e.g. enhancement, bug fix, tests).",
  "- Group related files under clear titles; do not repeat the PR bullet list verbatim.",
].join("\n");
