/** Prompt blocks for PR description generation (writing style, visuals, review map). */

export const descriptionBodyScaleGuidance = [
  "## Description body scale",
  "",
  "The server chooses body scale S, M, or L from workspace size stats and states the matching hard rule in the user message: bullet count, words per bullet, and technical depth.",
  "Bullets are short theme summaries; structural shape goes in visuals[].",
  "Match the depth the hard rule asks for: a larger change needs more detail, and a small one needs fewer bullets, with no empty or repeated ones.",
  "",
  "### Depth meanings",
  "- what_why: state what changed and why it matters for reviewers.",
  "- what_why_risk: also name notable risks, contracts, or failure modes the diff touches.",
  "- what_why_how: also name key modules or paths when a visual does not already show that interaction.",
].join("\n");

export const descriptionVisualsGuidance = [
  "## Visuals (visuals[])",
  "",
  "Visuals are the main place for structural shape. The kind menu, selection, payload rules, shape-only examples, and Mermaid rules live only here; quantity follows the visuals hard rule in the user message.",
  "Leave visuals out only when the inspected diff has no useful structural shape (pure copy, rename-only, or structure-free docs).",
  "",
  "### Bounded investigation",
  "- The description covers the files `listChangedFiles` lists and you inspected. When trusted context says `Change set truncated: yes`, or a tool returns `truncated`, the unlisted part stays undescribed.",
  "- A valid user supplement may narrow themes; it cannot change schema, tools, safety, or the single submit.",
  "- On large change sets, read the diffs that prove main behavior, contracts, ownership, and risk; diffing every path costs time without changing the themes.",
  "- Focused reads fill in ownership, type shape, or order the diff lacks.",
  "- Cluster hunks into themes. `description` is a markdown bullet list of short theme summaries, without headings (`##`, `###`) or fences, because it renders inside a section the server owns.",
  "- Choose visuals once the evidence is in, using only paths and names you read.",
  "",
  "### Selection",
  "For each proved theme:",
  "- Include a visual when it materially improves comprehension, and prefer one clear view over overlapping views.",
  "- Prefer `diff` whenever an existing shape changes (call/component/file trees, schemas, contracts, types, control flow); use the named non-diff kind when the resulting shape is clearer than a delta.",
  "- Use `full_block` when most of the shape is new or omitted context hides ownership or order.",
  "- Keep unchanged neighbors only for ownership, sequence, or boundary.",
  "- Include only proved names, calls, files, props, states, routes, fields, and boundaries.",
  "- Order visuals for the clearest review story, not by fixed kind order.",
  "- Structure a visual already shows stays out of the bullets.",
  "",
  "### Allowed kinds",
  "- pseudocode: logic or algorithm (`text` fence)",
  "- call_tree: resulting runtime call order (`text` fence); existing call-tree delta -> `diff`",
  "- component_tree: UI hierarchy with hooks/state/package bounds (`tsx` or `ts`); existing UI-tree delta -> `diff`",
  "- file_tree: file ownership or non-UI package responsibility (`text` fence); existing file-tree delta -> `diff`",
  "- mermaid: interaction/control/data flow that fits a flowchart (`flowchart LR` or `flowchart TB` only)",
  "- diff: delta of an existing schema, endpoint contract, central type, tree, or control-flow shape",
  "- full_block: mostly new schema, endpoint, type, or code shape (`text`, `ts`, or `tsx`)",
  "",
  "### Payload rules",
  "- Each entry needs `kind` and `content`. `content` is the inner sketch only; the server adds fences.",
  "- Only these seven kinds and the languages listed, because the server rejects anything else.",
  "- `language` belongs only on `component_tree` (`tsx` or `ts`) or `full_block` (`text`, `ts`, or `tsx`). Mermaid is its own kind, never a `full_block` language.",
  "- Visuals hold sketches of the inspected change set: no HTML fences, no links to files outside it, and no full git diff dump.",
  "- Represent SQL/JSON/Python-shaped changes with `diff` or `full_block` using only the allowed languages.",
  "- Place visuals after description bullets in submit order; the server renders all bullets, then all visuals.",
  "",
  "### Mermaid rules (GitHub must render it)",
  "- Kind must be `mermaid`. Inner content only (no nested fences or backticks).",
  "- First line: `flowchart LR` (preferred) or `flowchart TB`. No sequence or state diagrams.",
  '- Simple node ids (A, B, C…). Quoted labels: `A["Load course"]`. Edges with `-->`.',
  "- One connected graph. For large PRs use ≤8 nodes. No `/subroutine/` shapes.",
  "",
  "### Shape-only examples (enums and inner content only)",
  'Schema/endpoint diff: `{"kind":"diff","content":"- GET /users/:id\\n+ GET /users/:id\\n+   Authorization: Bearer <token>"}`',
  'Component tree with state: `{"kind":"component_tree","language":"tsx","content":"<CheckoutPage>\\n  useCart()\\n  <PayButton>"}`',
  'New type full_block: `{"kind":"full_block","language":"ts","content":"type Session = { id: string; expiresAt: number }"}`',
  'Mermaid flowchart: `{"kind":"mermaid","content":"flowchart LR\\n  A[\\"Admin form save\\"] --> B[\\"Render-safe redirect\\"]\\n  B --> C[\\"Next navigation\\"]"}`',
].join("\n");

export const descriptionReviewMapGuidance = [
  "## Review map (prFiles)",
  "",
  "The server chooses map mode from workspace size stats and states the active mode as a hard rule in the user message.",
  "",
  "### When mode is omit",
  "- The change set is small enough to read without a map, so the payload has no `prFiles`: type, short description bullets, and visuals.",
  "",
  "### When mode is read_first",
  "- `prFiles` has 1–5 entries: the files a reviewer should open first, not every changed file.",
  "- Order by review risk: auth, data, migrations, core API before tests, docs, or chore.",
  "- Each entry has exactly two fields:",
  "  - `filename` (a changed path from the PR)",
  "  - `changesTitle` (one short clause: why open this file first)",
  "- The map points to files; it does not restate the description bullets, group by PR-type labels, or carry per-file summaries (`changesSummary`) or `label`.",
].join("\n");
