/** Prompt blocks for PR description generation (writing style, Mermaid, review map). */

export const descriptionBodyScaleGuidance = [
  "## Description body scale",
  "",
  "The server chooses body scale from workspace size stats and injects a hard rule in the user message.",
  "Follow that rule for bullet count, words per bullet, and technical depth.",
  "Do not stay at a fixed short template when the hard rule asks for more detail.",
  "Do not pad with empty or repeated bullets when the hard rule asks for fewer.",
  "",
  "### Depth meanings",
  "- what_why: state what changed and why it matters for reviewers.",
  "- what_why_risk: also name notable risks, contracts, or failure modes the diff touches.",
  "- what_why_how: also name key modules or paths and how they interact.",
].join("\n");

export const descriptionMermaidGuidance = [
  "## Changes diagram (changesDiagram)",
  "",
  "Optional fenced ```mermaid flowchart LR``` showing one connected story across the main change.",
  "Omit changesDiagram when a diagram would not help reviewers.",
  "",
  "### Syntax rules (GitHub must render it)",
  "- First line inside the fence: `flowchart LR` (preferred) or `flowchart TB`.",
  '- Use simple node ids (A, B, C…). Put human text in **quoted** labels: `A["Load course"]`.',
  "- Do **not** use `/subroutine/` node shapes — slashes in labels break GitHub's parser.",
  "- Do **not** put `/`, backticks, or unescaped `()` inside unquoted `[labels]`.",
  "- One connected graph only (every node reachable); for large PRs use ≤8 nodes and group steps.",
  "- Edges: `A --> B` only (no exotic arrow types).",
  "",
  "### Large PR tips",
  '- Summarize areas (e.g. "Admin API", "Course builder") instead of listing every file.',
  "- Prefer one trunk flow with short labels over multiple disconnected mini-flows.",
  "",
  "### Good example",
  "```mermaid",
  "flowchart LR",
  '  A["Admin form save"] --> B["Render-safe redirect"]',
  '  B --> C["Next navigation"]',
  '  D["Course builder"] --> E["Paginated sections"]',
  '  E --> F["Lesson + subsection data"]',
  "```",
  "",
  "### Bad (will fail on GitHub)",
  "- `K[/api/admin-users/list proxy]` — slashes inside brackets.",
  "- Mixing four unrelated flows with no edges between them.",
  "- Labels with backticks or nested quotes.",
].join("\n");

export const descriptionReviewMapGuidance = [
  "## Review map (prFiles)",
  "",
  "Server chooses map mode from workspace size stats and injects a hard rule in the user message.",
  "Follow that rule exactly.",
  "",
  "### When mode is omit",
  "- Do **not** emit `prFiles`.",
  "- Publish type, description bullets, and optional Mermaid only.",
  "",
  "### When mode is read_first",
  "- Emit `prFiles` with **1–5** entries only (never more).",
  "- Order by review risk: auth, data, migrations, core API before tests, docs, or chore.",
  "- Each entry needs only:",
  "  - `filename` (a changed path from the PR)",
  "  - `changesTitle` (one short clause: why open this file first)",
  "- Do **not** restate the top description bullets.",
  "- Do **not** list every changed file.",
  "- Do **not** group by PR-type labels (enhancement, bug fix, …).",
  "- Do **not** emit multi-bullet per-file summaries (`changesSummary`) or grouping `label`.",
].join("\n");
