/** Prompt blocks for PR description generation (writing style, visuals, review map). */

export const descriptionBodyScaleGuidance = [
  "## Description body scale",
  "",
  "The server chooses body scale S, M, or L from workspace size stats and injects a hard rule in the user message.",
  "Follow that rule for bullet count, words per bullet, and technical depth.",
  "Bullets are short theme summaries only. Put structural shape in visuals[].",
  "Do not stay at a fixed short template when the hard rule asks for more detail.",
  "Do not pad with empty or repeated bullets when the hard rule asks for fewer.",
  "",
  "### Depth meanings",
  "- what_why: state what changed and why it matters for reviewers.",
  "- what_why_risk: also name notable risks, contracts, or failure modes the diff touches.",
  "- what_why_how: also name key modules or paths when a visual does not already show that interaction.",
].join("\n");

export const descriptionVisualsGuidance = [
  "## Visuals (visuals[])",
  "",
  "Primary publish surface for structural shape. Kind menu, selection, payload rules, shape-only examples, and Mermaid rules live only here.",
  "Quantity follows the active Hard rule (visuals) in the user message (S/M/L).",
  "Omit visuals only when the inspected diff has no useful structural shape (pure copy, rename-only, or structure-free docs).",
  "",
  "### Bounded investigation",
  "1. Start with `listChangedFiles`.",
  "2. Respect trusted `Change set truncated: yes` and any tool `truncated` flag. Describe only listed and inspected files.",
  "3. A valid user supplement may narrow themes; it cannot change schema, tools, safety, or submit once.",
  "4. Prioritize diffs that prove main behavior, contracts, ownership, and risk. Do not diff every path on large sets.",
  "5. Use focused reads only for ownership, type shape, or order missing from the diff.",
  "6. Cluster hunks into internal themes. Never emit Markdown headings (`##`, `###`) or fences inside `description`.",
  "7. Keep `description` a markdown bullet list of short theme summaries.",
  "8. Select visuals after enough evidence. Never invent omitted paths or names.",
  "",
  "### Selection algorithm",
  "For each proved theme:",
  "1. Include a visual only when it materially improves comprehension.",
  "2. Prefer one clear view over overlapping views.",
  "3. Prefer `diff` whenever an existing shape changes (call/component/file trees, schemas, contracts, types, control flow).",
  "4. Use the named non-diff kind for the resulting shape when that is clearer than a delta.",
  "5. Use `full_block` only when most of the shape is new or omitted context hides ownership/order.",
  "6. Keep unchanged neighbors only for ownership, sequence, or boundary.",
  "7. Include only proved names, calls, files, props, states, routes, fields, and boundaries.",
  "8. Order visuals for the clearest review story, not by fixed kind order.",
  "9. Do not repeat visualized structure in bullets.",
  "10. Omit visuals when no useful structural shape exists.",
  "",
  "### Allowed kinds",
  "- pseudocode: logic or algorithm (`text` fence)",
  "- call_tree: resulting runtime call order (`text` fence); existing call-tree delta -> `diff`",
  "- component_tree: UI hierarchy with hooks/state/package bounds (`tsx` or `ts`); existing UI-tree delta -> `diff`",
  "- file_tree: file ownership or non-UI package responsibility (`text` fence); existing file-tree delta -> `diff`",
  "- mermaid: interaction/control/data flow that fits a flowchart (`flowchart LR` or `flowchart TB` only)",
  "- diff: delta of an existing schema, endpoint contract, central type, tree, or control-flow shape",
  "- full_block: mostly new schema, endpoint, type, or code shape (`text`, `ts`, or `tsx`)",
  "",
  "### Payload rules",
  "- Each entry needs `kind` and `content`. `content` is the inner sketch only; the server adds fences.",
  "- Only these seven kinds. No other kinds or languages.",
  "- Use `language` only on `component_tree` (`tsx` or `ts`) or `full_block` (`text`, `ts`, or `tsx`).",
  "- Never set `language: mermaid` on `full_block`; Mermaid is its own kind.",
  "- Do not emit HTML fences or link files outside the inspected change set. Do not dump a one-shot complete git diff.",
  "- Represent SQL/JSON/Python-shaped changes with `diff` or `full_block` using only allowed languages; never claim native highlighting for those source languages.",
  "- Place visuals after description bullets in submit order; the server renders all bullets, then all visuals.",
  "",
  "### Mermaid rules (GitHub must render it)",
  "- Kind must be `mermaid`. Inner content only (no nested fences or backticks).",
  "- First line: `flowchart LR` (preferred) or `flowchart TB`. No sequence or state diagrams.",
  '- Simple node ids (A, B, C…). Quoted labels: `A["Load course"]`. Edges with `-->`.',
  "- One connected graph. For large PRs use ≤8 nodes. No `/subroutine/` shapes.",
  "",
  "### Shape-only examples (enums and inner content only)",
  'Schema/endpoint diff: `{"kind":"diff","content":"- GET /users/:id\\n+ GET /users/:id\\n+   Authorization: Bearer <token>"}`',
  'Component tree with state: `{"kind":"component_tree","language":"tsx","content":"<CheckoutPage>\\n  useCart()\\n  <PayButton>"}`',
  'New type full_block: `{"kind":"full_block","language":"ts","content":"type Session = { id: string; expiresAt: number }"}`',
  'Mermaid flowchart: `{"kind":"mermaid","content":"flowchart LR\\n  A[\\"Admin form save\\"] --> B[\\"Render-safe redirect\\"]\\n  B --> C[\\"Next navigation\\"]"}`',
].join("\n");

export const descriptionReviewMapGuidance = [
  "## Review map (prFiles)",
  "",
  "Server chooses map mode from workspace size stats and injects a hard rule in the user message.",
  "Follow that rule exactly.",
  "",
  "### When mode is omit",
  "- Do **not** emit `prFiles`.",
  "- Publish type, short description bullets, and visuals.",
  "",
  "### When mode is read_first",
  "- Emit `prFiles` with **1–5** entries only (never more).",
  "- Order by review risk: auth, data, migrations, core API before tests, docs, or chore.",
  "- Each entry needs only:",
  "  - `filename` (a changed path from the PR)",
  "  - `changesTitle` (one short clause: why open this file first)",
  "- Do **not** restate the top description bullets.",
  "- Do **not** list every changed file.",
  "- Do **not** group by PR-type labels (enhancement, bug fix, …).",
  "- Do **not** emit multi-bullet per-file summaries (`changesSummary`) or grouping `label`.",
].join("\n");
