import {
  COMMAND_FEATURE_MODES,
  DEFAULT_FEATURE_ASK,
  DEFAULT_FEATURE_COMMIT_STATUS,
  DEFAULT_FEATURE_DESCRIBE,
  DEFAULT_FEATURE_REVIEW,
  DEFAULT_FEATURE_REVIEW_LABELS,
  DEFAULT_FEATURE_TITLE_REWRITE,
  DEFAULT_FEATURE_TRIAGE,
  DEFAULT_FEATURE_VERIFICATION,
  DESCRIBE_FEATURE_MODES,
  REVIEW_FEATURE_MODES,
  REVIEW_LABELS_MODES,
  VERIFICATION_FEATURE_MODES,
  type Features,
} from "../featureModes.js";
import { ENV } from "../envKeys.js";
import { readEnum, readStrictBoolean } from "../envReaders.js";

export function readFeatures(): Features {
  return {
    review: readEnum(ENV.FEATURE_REVIEW, REVIEW_FEATURE_MODES, DEFAULT_FEATURE_REVIEW),
    describe: readEnum(ENV.FEATURE_DESCRIBE, DESCRIBE_FEATURE_MODES, DEFAULT_FEATURE_DESCRIBE),
    verification: readEnum(
      ENV.FEATURE_VERIFICATION,
      VERIFICATION_FEATURE_MODES,
      DEFAULT_FEATURE_VERIFICATION,
    ),
    ask: readEnum(ENV.FEATURE_ASK, COMMAND_FEATURE_MODES, DEFAULT_FEATURE_ASK),
    triage: readEnum(ENV.FEATURE_TRIAGE, COMMAND_FEATURE_MODES, DEFAULT_FEATURE_TRIAGE),
    reviewLabels: readEnum(
      ENV.FEATURE_REVIEW_LABELS,
      REVIEW_LABELS_MODES,
      DEFAULT_FEATURE_REVIEW_LABELS,
    ),
    commitStatus: readStrictBoolean(ENV.FEATURE_COMMIT_STATUS, DEFAULT_FEATURE_COMMIT_STATUS),
    titleRewrite: readStrictBoolean(ENV.FEATURE_TITLE_REWRITE, DEFAULT_FEATURE_TITLE_REWRITE),
  } satisfies Features;
}
