/** Default values for env-backed settings (see `docs/configuration.md`). */

export const DEFAULT_PORT = 3000;
export const DEFAULT_ROLE = "web" as const;

export const DEFAULT_AGENT_PROVIDER = "pi" as const;
export const DEFAULT_PI_PROVIDER = "openai";
export const DEFAULT_PI_MODEL = "gpt-4o-mini";
export const DEFAULT_PROVIDER_PROMPT_TIMEOUT_MS = 300_000;

export const DEFAULT_MAX_TOOL_ROUNDS = 24;
export const DEFAULT_MAX_REVIEW_PUBLISH_ATTEMPTS = 3;
export const DEFAULT_MAX_REVIEW_PUBLISH_CALLS = 2;
export const DEFAULT_REVIEW_MIN_CONFIDENCE = 1;

export const DEFAULT_REVIEW_CONCURRENCY = 2;
export const DEFAULT_ASK_CONCURRENCY = 1;
export const DEFAULT_ACK_CONCURRENCY = 2;
export const DEFAULT_DESCRIPTION_CONCURRENCY = 1;
export const DEFAULT_TRIAGE_CONCURRENCY = 1;

export const DEFAULT_MAX_TOOL_ROUNDS_DESCRIBE = 16;
export const DEFAULT_MAX_TOOL_ROUNDS_TRIAGE = 32;
export const DEFAULT_MAX_TRIAGE_FIXES_PER_RUN = 10;
export const DEFAULT_DESCRIPTION_GENERATE_TITLE = false;
export const DEFAULT_SLASH_ALLOWED_ASSOCIATIONS = "OWNER,MEMBER,COLLABORATOR";

export const DEFAULT_QUEUE_RETRY_LIMIT = 3;
export const DEFAULT_QUEUE_RETRY_DELAY_SECONDS = 30;
export const DEFAULT_QUEUE_RETRY_DELAY_MAX_SECONDS = 300;
export const DEFAULT_QUEUE_EXPIRE_IN_SECONDS = 3600;
export const DEFAULT_QUEUE_HEARTBEAT_SECONDS = 60;
export const DEFAULT_QUEUE_POLLING_INTERVAL_SECONDS = 0.5;
export const DEFAULT_QUEUE_RETENTION_SECONDS = 1_209_600;
export const DEFAULT_QUEUE_DELETE_AFTER_SECONDS = 604_800;
export const DEFAULT_SHUTDOWN_DRAIN_TIMEOUT_SECONDS = 25;

export const DEFAULT_WEBHOOK_EVENTS_RETENTION_SECONDS = 2_592_000;
export const DEFAULT_AGENT_WORK_RETENTION_SECONDS = 2_592_000;
export const DEFAULT_RETENTION_CRON = "17 3 * * *";
export const DEFAULT_RETENTION_ENABLED = true;
export const DEFAULT_INSTALLATION_GROUP_CONCURRENCY = 2;

export const DEFAULT_MAX_ASK_TOOL_ROUNDS = 12;
export const DEFAULT_MAX_ASK_FINALIZE_ROUNDS = 2;

export const DEFAULT_WEBHOOK_MAX_BODY_BYTES = 25_000_000;
export const DEFAULT_WEBHOOK_TIMEOUT_MS = 10_000;

export const DEFAULT_CONTEXT7_API_KEY = "";
export const DEFAULT_CURSOR_API_KEY = "";

export const DEFAULT_ENABLE_REVIEW_LABELS_EFFORT = true;
export const DEFAULT_ENABLE_REVIEW_LABELS_SECURITY = false;
export const DEFAULT_ENABLE_THREAD_REPLIES = false;
export const DEFAULT_ENABLE_REVIEW_COMMIT_STATUS = false;
export const DEFAULT_DESCRIPTION_AUTO_ACTIONS = "opened";
/** Default `pull_request` actions that auto-run `/review`. "opened" only so a PR is reviewed once at the start; follow-up pushes require a manual `/review`. */
export const DEFAULT_REVIEW_AUTO_ACTIONS = "opened";

export const DEFAULT_MAX_PR_FILES_LISTED = 300;
export const DEFAULT_MAX_PR_FILES_PATCH_BYTES = 500_000;

export const DEFAULT_LOG_LEVEL = "info" as const;
export const DEFAULT_LOG_MAX_WIDE_EVENTS = 128;
export const DEFAULT_LOG_REDACT = true;

export const DEFAULT_REVIEW_INJECT_ANCHOR_MENU = true;
export const DEFAULT_REVIEW_REQUIRE_DIFF_CACHE_BEFORE_SUBMIT = true;
export const DEFAULT_REVIEW_ANCHOR_MENU_MAX_FILES = 40;
export const DEFAULT_REVIEW_ANCHOR_MENU_MAX_RANGES_PER_FILE = 20;

export const DEFAULT_LOCAL_WORKSPACE_CLONE_TIMEOUT_MS = 60_000;
export const DEFAULT_LOCAL_WORKSPACE_FETCH_TIMEOUT_MS = 60_000;
export const DEFAULT_LOCAL_WORKSPACE_SEARCH_MAX_FILES = 500;
export const DEFAULT_LOCAL_WORKSPACE_MAX_FILE_BYTES = 1_000_000;
export const DEFAULT_LOCAL_WORKSPACE_SEARCH_MAX_TOTAL_BYTES = 50_000_000;
export const DEFAULT_LOCAL_WORKSPACE_MAX_DIFF_BYTES = 5_000_000;
export const DEFAULT_LOCAL_WORKSPACE_READ_RESPONSE_BYTES = 128_000;
export const DEFAULT_LOCAL_WORKSPACE_DIFF_RESPONSE_BYTES = 256_000;
export const DEFAULT_CONTEXT7_RESPONSE_BYTES = 64_000;
export const DEFAULT_LOCAL_WORKSPACE_MIN_FREE_SPACE_BYTES = 500_000_000;
export const DEFAULT_LOCAL_WORKSPACE_MAX_FETCH_BYTES = 2 * 1024 * 1024 * 1024;
export const DEFAULT_LOCAL_WORKSPACE_FULL_CLONE_MAX_REPO_KB = 1_000_000;
export const DEFAULT_LOCAL_WORKSPACE_STALE_CLEANUP_AGE_SECONDS = 86_400;
