export const LOCAL_WORKSPACE_TREE_WALK_CONCURRENCY = 32;
export const LOCAL_WORKSPACE_GREP_PATHSPEC_CHUNK_SIZE = 256;
export const PR_REPOSITORY_VIEW_RELEASE_GRACE_MS = 60_000;

/** Local PR workspace caps. */
export const LOCAL_WORKSPACE_CLONE_TIMEOUT_MS = 60_000;
export const LOCAL_WORKSPACE_FETCH_TIMEOUT_MS = 60_000;
export const LOCAL_WORKSPACE_SEARCH_MAX_FILES = 500;
export const LOCAL_WORKSPACE_MAX_FILE_BYTES = 1_000_000;
export const LOCAL_WORKSPACE_SEARCH_MAX_TOTAL_BYTES = 50_000_000;
export const LOCAL_WORKSPACE_MAX_DIFF_BYTES = 5_000_000;
export const LOCAL_WORKSPACE_READ_RESPONSE_BYTES = 128_000;
export const LOCAL_WORKSPACE_DIFF_RESPONSE_BYTES = 256_000;
export const LOCAL_WORKSPACE_MIN_FREE_SPACE_BYTES = 500_000_000;
export const LOCAL_WORKSPACE_MAX_FETCH_BYTES = 2 * 1024 * 1024 * 1024;
export const LOCAL_WORKSPACE_FULL_CLONE_MAX_REPO_KB = 1_000_000;
export const LOCAL_WORKSPACE_STALE_CLEANUP_AGE_SECONDS = 86_400;
export const LOCAL_WORKSPACE_SYMBOL_INDEX_BUILD_TIMEOUT_MS = 5_000;
export const LOCAL_WORKSPACE_SYMBOL_INDEX_MAX_SYMBOLS = 50_000;
export const LOCAL_WORKSPACE_SYMBOL_INDEX_MAX_RESULTS = 50;
