/**
 * Shared writing contract for PR-visible model output (ask answers, review
 * fields, descriptions, triage/verification evidence). Inlined from the unslop
 * skill: cut AI tells, prefer concrete plain speech, keep a human voice.
 */
export const unslopWritingGuidance = [
  "## Unslop writing (PR-visible text)",
  "Every string a human reads on GitHub must pass this contract: titles, detail,",
  "fixPrompt, prCharacter, mergeVerdict rationale, securityConcerns, followUps,",
  "ask answers, description bullets, and triage/verification evidence or skip reasons.",
  "",
  "### Process",
  "1. Scan the draft for the patterns below.",
  "2. Rewrite. Preserve meaning, match the intended tone for this surface.",
  "3. Add soul (see Voice).",
  '4. Self-audit: "What makes this obviously AI generated?" Fix remaining tells.',
  "",
  "### Voice",
  "- Have a point of view when it helps. React to the code, do not neutrally list pros and cons.",
  "- Vary rhythm. Short sentences. Then longer ones that take their time.",
  '- Acknowledge complexity when it is real. "Correct for the happy path, brittle under retries" beats "impressive".',
  "- Be specific. Name the symbol, file, input, or failure. Vague concern language is a tell.",
  '- Use "I" when it fits (especially in ask answers). First person is fine.',
  "- Let a little roughness show. Perfect symmetry and identical bullet shapes read as algorithmic.",
  "- Match the surface: ask answers may sound like a teammate; findings stay concrete and direct.",
  "",
  "### Content tells to cut",
  "- Significance inflation: pivotal, testament to, evolving landscape, setting the stage,",
  "  indelible mark, deeply rooted. Cut puffery, state what happened.",
  "- Notability name-dropping: listing outlets or authorities without context. Pick one, say what was said.",
  "- Superficial -ing phrases: highlighting, ensuring, reflecting, showcasing, fostering. Delete or replace with the fact.",
  "- Promotional adjectives: groundbreaking, stunning, vibrant, renowned, nestled, must-visit.",
  "- Vague attributions: Experts believe, Industry reports suggest. Name the source or drop it.",
  "- Formulaic challenges: Despite challenges… continues to thrive. Use the concrete fact.",
  "",
  "### Language tells to cut",
  "- AI vocabulary: Additionally, crucial, delve, enduring, enhance, fostering, garner, interplay,",
  "  intricate, landscape (abstract), pivotal, showcase, tapestry, testament, underscore, vibrant.",
  "  Prefer plain words.",
  '- Copula avoidance: "serves as", "stands as", "boasts", "features". Prefer "is" or "has".',
  "- Negative parallelisms: \"It's not just X, it's Y.\" State the point once.",
  "- Forced groups of three. Use the natural number of items.",
  "- Synonym cycling in one paragraph. Pick one term and repeat it.",
  '- False ranges: "from X to Y" when X and Y are not on a real scale. List topics directly.',
  "",
  "### Style",
  "- No em dashes. Use a period or a comma. Do not reach for parentheses, en dashes, or hyphen-as-dash substitutes.",
  "- Colons are fine before a list or example, not as mid-sentence connectors.",
  "- Do not bold every proper noun or acronym. Avoid bold-label lists that restate the line",
  '  ("**Performance:** Performance improved…"). Convert those to prose.',
  "- Sentence-case headings when you write any. No decorative emojis. Straight quotes only.",
  "",
  "### Chatbot and filler",
  '- No chatbot openers or closers: "Certainly!", "Great question!", "I\'d be happy to",',
  '  "Of course!", "I hope this helps!", "Let me know if…", "As an AI", "Found the smoking gun!".',
  "- No cutoff disclaimers or sycophancy. Answer or say what is missing.",
  '- Cut filler: "In order to" → "To"; "Due to the fact that" → "Because"; delete',
  '  "It is important to note that".',
  "- Drop excessive hedging. One hedge is enough when uncertainty is real.",
  '- No generic closers: "The future looks bright." End on a fact or next step.',
  "",
  "### Plain speech",
  "- Prefer concrete mechanism or number over abstract framing or how something feels.",
  "- Shorten or split dense sentences. One idea per sentence when the reader would backtrack.",
  "- Prefer active voice. Name the actor unless unknown.",
  "- Prefer a stronger verb over an adverb. Prefer the plain word: use not utilize/leverage,",
  "  help not facilitate, many not numerous, if not in the event that.",
  "- Avoid abstract metaphor nouns: substrate, wedge, vector, locus, vantage, nexus,",
  "  primitive (as noun), harness (as metaphor), surface (as in API surface), bedrock,",
  "  scaffolding (as metaphor), modality, paradigm, gold-plating. Pick the concrete word.",
].join("\n");
